openapi: 3.0.1
info:
  title: Data Ingestion API
  description: |-
    Data Ingestion allows you to bring your data into Adobe Experience
    Platform through batch ingestion and streaming ingestion. Batch ingestion lets
    you import data in batch, from any number of data sources. Streaming ingestion
    lets users send data to Platform in real time from client and server-side devices.

    - Related Documentation:
      - [Data ingestion documentation](http://www.adobe.com/go/data-ingestion-overview-en)

    - Visualize API calls with Postman (a free, third-party software):
      - [Data Ingestion Service API Postman collection on GitHub](https://github.com/adobe/experience-platform-postman-samples/blob/master/apis/experience-platform/Data%20Ingestion%20API.postman_collection.json)
      - [Video guide for creating the Postman environment](https://video.tv.adobe.com/v/28832)
      - [Steps for importing environments and collections in Postman](https://learning.getpostman.com/docs/postman/collection_runs/using_environments_in_collection_runs/)
    
    - API paths:
      - Base path for batch ingestion APIs: https://<span>platform.adobe.io/data/foundation/import
      - Base path for streaming ingestion APIs:
        - Data inlet management: https://<span>platform.adobe.io/data/core/edge
        - Data collection: https://<span>dcs.adobedc.net/
        - Example of a complete path for batch ingestion: https://<span>platform.adobe.io/data/foundation/import/batches
        - Example of a complete path for streaming ingestion: https://<span>platform.adobe.io/data/foundation/import/collection/{CONNECTION_ID}
    
    - Required headers:
      - All calls require the headers `Authorization`, `x-gw-ims-org-id`,
      and `x-api-key`. For more information on how to obtain these values, see the
      [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
      - All resources in Experience Platform are isolated to specific virtual sandboxes. 
      All requests to Platform APIs require the header `x-sandbox-name` whose value is 
      the all-lowercase name of the sandbox the operation will take place in (for example,
      "prod\"). See the [sandboxes overview](https://adobe.com/go/sandbox-overview-en) for 
      more information.
      - Requests with a payload in the request body (such as POST, PUT, and PATCH calls) 
      may require the header `Content-Type`. Accepted values specific to each call are 
      provided in the call parameters.
  version: "1.0"
servers:
- url: //platform.adobe.io/data/foundation/import
tags:
- name: Batch Ingestion
  description: 'Batch ingestion is used to ingest data into Experience Platform as
    batch files. For example, data being ingested can be the profile data from a flat
    file in a CRM system (for example: Parquet or JSON) or data that conforms to a
    known Experience Data Model (XDM) schema within the Schema Registry.'
- name: Streaming Ingestion
  description: Streaming ingestion allows you to send data from client and server-side
    devices to Experience Platform in real-time. It drives Real-time Customer Profile
    creating personalized experiences.
paths:
  /collection/{CONNECTION_ID}:
    post:
      tags:
      - Streaming Ingestion
      summary: Send messages to Adobe Experience Platform
      operationId: sendMessage
      parameters:
      - name: Authorization
        in: header
        description: The access token which can be copied from your Experience Platform
          integration, prefixed with "Bearer ". For more information on how to obtain
          this value, visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: The media type being sent in the request payload. For JSON formatted
          payloads the value must be set to application/json. The endpoint also accepts
          payloads encoded in Smile format, which requires the value to be set to
          application/x-jackson-smile.
        required: true
        schema:
          type: string
          enum:
          - application/json
          - application/x-jackson-smile
      - name: Cache-Control
        in: header
        schema:
          type: string
          enum:
          - no-cache
      - name: CONNECTION_ID
        in: path
        description: The ID of the streaming connection you want to stream data to.
        required: true
        schema:
          type: string
      - name: syncValidation
        in: query
        description: |-
          An optional query parameter, intended for development purposes. If set to `true`, it can be used for immediate feedback to determine if the request was successfully sent. By default, this value is set to `false`.

           Please note that requests using this query parameter are __limited__ to 60 requests per minute, per CONNECTION_ID.
        schema:
          type: boolean
          enum:
          - true
          - false
      requestBody:
        description: The data that you want to ingest to Platform.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/streamingMessage'
        required: true
      responses:
        200:
          description: The data was successfully ingested.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamingIngestionResponse'
        400:
          description: There was a problem with the request. See the response body
            for a more specific error message.
          content: {}
        401:
          description: Access is unauthorized. The user needs to provide a valid bearer
            token.
          content: {}
        403:
          description: Access is forbidden.
          content: {}
        413:
          description: The payload is larger than 1 MB.
          content: {}
        429:
          description: Too many requests. The service is experiencing high loads.
          content: {}
        500:
          description: An internal server error has ocurred.
          content: {}
        503:
          description: The service is currently unavailable. Clients should retry
            at least three times using an exponential back-off strategy.
          headers:
            Retry-After:
              description: Specifies the number of seconds to retry after.
              schema:
                type: integer
          content: {}
      x-codegen-request-body-name: body
  /collection/batch/{CONNECTION_ID}:
    post:
      tags:
      - Streaming Ingestion
      summary: Send multiple messages to Adobe Experience Platform
      operationId: postBatchOfStreamingMessages
      parameters:
      - name: Authorization
        in: header
        description: The access token which can be copied from your Experience Platform
          integration, prefixed with "Bearer ". For more information on how to obtain
          this value, visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: The media type being sent in the request payload. For JSON formatted
          payloads the value must be set to application/json. The endpoint also accepts
          payloads encoded in Smile format, which requires the value to be set to
          application/x-jackson-smile.
        required: true
        schema:
          type: string
          enum:
          - application/json
          - application/x-jackson-smile
      - name: CONNECTION_ID
        in: path
        description: The ID of the streaming connection you want to stream data to.
        required: true
        schema:
          type: string
      requestBody:
        description: The data that you want to ingest to Platform.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchMessage'
        required: true
      responses:
        207:
          description: A multi-status code. The recipient needs to consult the contents
            of the multi-status response body for further information about the success
            or failure of the method execution.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponseDTO'
        400:
          description: There was a problem with the request. See the response body
            for a more specific error message.
          content: {}
        401:
          description: Access is unauthorized. The user needs to provide a valid bearer
            token.
          content: {}
        403:
          description: Access is forbidden.
          content: {}
        413:
          description: The payload is larger than 1 MB.
          content: {}
        429:
          description: Too many requests. The service is experiencing high loads.
          content: {}
        500:
          description: An internal server error has occurred.
          content: {}
        503:
          description: The service is currently unavailable. Clients should retry
            at least three times using an exponential back-off strategy.
          headers:
            Retry-After:
              description: Specifies the number of seconds to retry after.
              schema:
                type: integer
          content: {}
      x-codegen-request-body-name: body
  /batches:
    post:
      tags:
      - Batch Ingestion
      summary: Create a new batch
      operationId: createBatch
      parameters:
      - name: Authorization
        in: header
        description: The access token which can be copied from your Experience Platform
          integration, prefixed with "Bearer ". For more information on how to obtain
          this value, visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-api-key
        in: header
        description: The API key which can be copied from your Experience Platform
          integration. For more information on how to obtain this value, visit the
          [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-gw-ims-org-id
        in: header
        description: The Organization ID which can be copied from your Experience
          Platform integration. For more information on how to obtain this value,
          visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-sandbox-name
        in: header
        description: The name of the sandbox in which the operation will take place.
          See the [sandboxes overview documentation](https://adobe.com/go/sandbox-overview-en)
          for more information.
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: application/json
        required: true
        schema:
          type: string
      requestBody:
        description: The payload that contains information needed to create
          a batch. 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestBatch'
        required: true
      responses:
        201:
          description: The batch was successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Batch'
        400:
          description: A bad request. The request is malformed.
          content: {}
        401:
          description: Access is unauthorized. The user needs to provide a valid bearer
            token.
          content: {}
        414:
          description: The URL length exceeds the allowed 2000 characters.
          content: {}
        500:
          description: An internal server error has occurred.
          content: {}
        503:
          description: The service is currently unavailable.
          content: {}
      x-codegen-request-body-name: body
  /batches/{batchId}/datasets/{datasetId}/files/{filePath}:
    put:
      tags:
      - Batch Ingestion
      summary: Upload a small file to a dataset
      description: |-
        This endpoint lets you upload files under datasets for a batch initialized by the bulk 
        ingestion API. The PUT method creates or updates the entire request stream as the file 
        bytes under the path denoted by the `filePath` and is idempotent. Subsequent calls to 
        this endpoint will replace the existing file on the referenced path. 
        **Note:** Due to gateway size and timeout limits, there is currently a size threshold of 256MB.
        If the file is larger than that, you **must** use the large file upload mechanism.
      operationId: uploadSmallFile
      parameters:
      - name: Authorization
        in: header
        description: The access token which can be copied from your Experience Platform
          integration, prefixed with "Bearer ". For more information on how to obtain
          this value, visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-api-key
        in: header
        description: The API key which can be copied from your Experience Platform
          integration. For more information on how to obtain this value, visit the
          [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-gw-ims-org-id
        in: header
        description: The Organization ID which can be copied from your Experience
          Platform integration. For more information on how to obtain this value,
          visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-sandbox-name
        in: header
        description: The name of the sandbox in which the operation will take place.
          See the [sandboxes overview documentation](https://adobe.com/go/sandbox-overview-en)
          for more information.
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: The type of content being sent in the body of the request. The value should 
          be 'application/octet-stream'.
        required: true
        schema:
          type: string
      - name: batchId
        in: path
        description: The ID of the batch that the data is being uploaded to.
        required: true
        schema:
          type: string
      - name: datasetId
        in: path
        description: The ID of the dataset that the data is being uploaded to.
        required: true
        schema:
          type: string
      - name: filePath
        in: path
        description: The location where the file will be uploaded to, on the Adobe
          side. **Note:** The directory structure denoted in this path is preserved
          and can be used to denote partitions that the file data belongs to.
        required: true
        schema:
          type: string
      responses:
        200:
          description: The file was successfully updated.
          content: {}
        201:
          description: The file was successfully created.
          content: {}
        400:
          description: The request is malformed.
          content: {}
        401:
          description: Access is unauthorized. The IMS token provided is invalid.
          content: {}
        404:
          description: The batch or dataset resource is not found.
          content: {}
        414:
          description: The URL length exceeds the allowed 2000 characters.
          content: {}
        415:
          description: The uploaded file media type isn't supported.
          content: {}
        503:
          description: The service is unavailable.
          content: {}
    patch:
      tags:
      - Batch Ingestion
      summary: Upload part of a large file to a batch
      description: Files larger than 256MB are uploaded in parts. The PATCH endpoint
        provides you a way to upload a part of your large file that was initialized
        via the POST endpoint.
      operationId: uploadLargeFilePart
      parameters:
      - name: Authorization
        in: header
        description: The access token which can be copied from your Experience Platform
          integration, prefixed with "Bearer ". For more information on how to obtain
          this value, visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-api-key
        in: header
        description: The API key which can be copied from your Experience Platform
          integration. For more information on how to obtain this value, visit the
          [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-gw-ims-org-id
        in: header
        description: The Organization ID which can be copied from your Experience
          Platform integration. For more information on how to obtain this value,
          visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-sandbox-name
        in: header
        description: The name of the sandbox in which the operation will take place.
          See the [sandboxes overview documentation](https://adobe.com/go/sandbox-overview-en)
          for more information.
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        required: true
        description: The type of content being sent in the body of the request. The value should 
          be 'application/octet-stream'.
        schema:
          type: string
          enum:
          - application/octet-stream
      - name: batchId
        in: path
        description: The ID of the batch that the data is being uploaded to.
        required: true
        schema:
          type: string
      - name: datasetId
        in: path
        description: The ID of the dataset that the data is being uploaded to.
        required: true
        schema:
          type: string
      - name: filePath
        in: path
        description: The location where the file will be uploaded to, on the Adobe
          side. **Note:** The directory structure denoted in this path is preserved
          and can be used to denote partitions that the file data belongs to.
        required: true
        schema:
          type: string
      - name: Content-Range
        in: header
        description: The lowest and highest value of bytes in the file being uploaded with this request.
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - file
              properties:
                file:
                  type: string
                  description: The full path and name of the file you are trying to upload. This file path 
                    is the local file path with the file format suffix. 
                    For example, `@{FILE_PATH_AND_NAME}.parquet`. **Note**, as the 'application/octet-stream' 
                    content type is a binary file that contains data in the form of bytes instead of text, no 
                    example request body is provided here.
                  format: binary
        required: true
      responses:
        200:
          description: The file was successfully uploaded.
          headers:
            Range:
              description: The accepted range of content bytes is 0 - 512000000.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        400:
          description: The request is malformed.
          content: {}
        401:
          description: Access is unauthorized. The IMS token provided is invalid.
          content: {}
        404:
          description: The batch, dataset, or file resource is not found.
          content: {}
        414:
          description: The URL length exceeds the allowed 2000 characters.
          content: {}
        415:
          description: The uploaded file media type isn't supported.
          content: {}
        500:
          description: An internal server error has occurred.
          content: {}
        503:
          description: The service is unavailable.
          content: {}
    post:
      tags:
      - Batch Ingestion
      summary: Either initialize or finish uploading a large file
      description: This endpoint should only be used when uploading a large file to
        the batch. Large file upload should be used for files larger than 256MB.
      operationId: completeLargeFileUpload
      parameters:
      - name: Authorization
        in: header
        description: The access token which can be copied from your Experience Platform
          integration, prefixed with "Bearer ". For more information on how to obtain
          this value, visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-api-key
        in: header
        description: The API key which can be copied from your Experience Platform
          integration. For more information on how to obtain this value, visit the
          [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-gw-ims-org-id
        in: header
        description: The Organization ID which can be copied from your Experience
          Platform integration. For more information on how to obtain this value,
          visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-sandbox-name
        in: header
        description: The name of the sandbox in which the operation will take place.
          See the [sandboxes overview documentation](https://adobe.com/go/sandbox-overview-en)
          for more information.
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: The type of content being sent in the body of the request. The value should be 'application/json'.
        required: true
        schema:
          type: string
      - name: batchId
        in: path
        description: The ID of the batch that the data is being uploaded to.
        required: true
        schema:
          type: string
      - name: datasetId
        in: path
        description: The ID of the dataset that the data is being uploaded to.
        required: true
        schema:
          type: string
      - name: filePath
        in: path
        description: The location of the file you want to initialize or complete,
          within the Adobe data lake. **Note:** The directory structure denoted in this path
          is preserved and can be used to denote partitions that the file data belongs
          to.
        required: true
        schema:
          type: string
      - name: action
        in: query
        description: The action to perform on the file. Currently, the supported values
          are "INITIALIZE" and "COMPLETE". To begin initializing the file for upload,
          use the value "INITIALIZE". To mark the file as finished, use the value
          "COMPLETE".
        required: true
        schema:
          type: string
          enum:
          - INITIALIZE
          - COMPLETE
      responses:
        200:
          description: The file is now finished uploading.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        400:
          description: The request is malformed.
          content: {}
        401:
          description: Access is unauthorized. The IMS token provided is invalid.
          content: {}
        404:
          description: The batch, dataset, or file resource is not found.
          content: {}
        414:
          description: The URL length exceeds the allowed 2000 characters.
          content: {}
        500:
          description: An internal server error has occurred.
          content: {}
        503:
          description: The service is unavailable.
          content: {}
    head:
      tags:
      - Batch Ingestion
      summary: Get the current status of the large file
      description: Files larger than 256MB are uploaded in parts. The HEAD endpoint
        provides a way to get the byte range information received by the server so
        far.
      operationId: getLargeFileStatus
      parameters:
      - name: Authorization
        in: header
        description: The access token which can be copied from your Experience Platform
          integration, prefixed with "Bearer ". For more information on how to obtain
          this value, visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-api-key
        in: header
        description: The API key which can be copied from your Experience Platform
          integration. For more information on how to obtain this value, visit the
          [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-gw-ims-org-id
        in: header
        description: The Organization ID which can be copied from your Experience
          Platform integration. For more information on how to obtain this value,
          visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-sandbox-name
        in: header
        description: The name of the sandbox in which the operation will take place.
          See the [sandboxes overview documentation](https://adobe.com/go/sandbox-overview-en)
          for more information.
        required: true
        schema:
          type: string
      - name: batchId
        in: path
        description: The ID of the batch that the data is being uploaded to.
        required: true
        schema:
          type: string
      - name: datasetId
        in: path
        description: The ID of the dataset that the data is being uploaded to.
        required: true
        schema:
          type: string
      - name: filePath
        in: path
        description: The location of the file you want to retrieve status information
          about, within the Adobe data lake. **Note:** The directory structure denoted in this
          path is preserved and can be used to denote partitions that the file data
          belongs to.
        required: true
        schema:
          type: string
      responses:
        200:
          description: The status information was successfully returned.
          headers:
            Range:
              description: bytes 0-512000000
              schema:
                type: string
          content: {}
        400:
          description: The request is malformed.
          content: {}
        401:
          description: Access is unauthorized. The IMS token provided is invalid.
          content: {}
        404:
          description: The batch, dataset, or file resource is not found.
          content: {}
        414:
          description: URL length exceeds the allowed 2000 characters.
          content: {}
        415:
          description: The uploaded file media type isn't supported.
          content: {}
        500:
          description: An internal server error has occurred.
          content: {}
        503:
          description: The service is unavailable.
          content: {}  
  /batches/{batchId}/datasets/{datasetId}/preview:
    get:
      tags:
      - Batch Ingestion
      summary: Retrieve a preview for a batch
      description: Generates a data preview for the files uploaded to the batch so
        far. The preview can be generated for all the batch datasets collectively
        or for the selected datasets.
      operationId: retrievePreview
      parameters:
      - name: Authorization
        in: header
        description: The access token which can be copied from your Experience Platform
          integration, prefixed with "Bearer ". For more information on how to obtain
          this value, visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-api-key
        in: header
        description: The API key which can be copied from your Experience Platform
          integration. For more information on how to obtain this value, visit the
          [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-gw-ims-org-id
        in: header
        description: The Organization ID which can be copied from your Experience
          Platform integration. For more information on how to obtain this value,
          visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-sandbox-name
        in: header
        description: The name of the sandbox in which the operation will take place.
          See the [sandboxes overview documentation](https://adobe.com/go/sandbox-overview-en)
          for more information.
        required: true
        schema:
          type: string
      - name: batchId
        in: path
        description: The ID of the batch that you are trying to preview.
        required: true
        schema:
          type: string
      - name: datasetId
        in: path
        description: The ID of the dataset that you are trying to preview.
        required: true
        schema:
          type: string
      - name: format
        in: query
        description: The file format for the uploaded file.
        required: true
        schema:
          type: string
      - name: delimiter
        in: query
        description: The character used to specify boundaries between separate strings when parsing column values.
        schema:
          type: string
          default: ','
      - name: quote
        in: query
        description: The character used to quote a value when parsing data.
        schema:
          type: string
          default: '"'
      - name: escape
        in: query
        description: The character used to escape a reserved character when parsing data.
        schema:
          type: string
          default: \
      - name: charset
        in: query
        description: The character encoding used for parsing data.
        schema:
          type: string
          default: UTF-8
      - name: header
        in: query
        description: The flag to indicate if the header is supplied in the dataset
          files.
        schema:
          type: boolean
          default: true
      - name: nrow
        in: query
        description: The number of rows to parse.
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        200:
          description: The preview for the batch was successfully generated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PreviewResponse'
        400:
          description: The request is malformed.
          content: {}
        401:
          description: Access is unauthorized. The IMS token provided is invalid.
          content: {}
        404:
          description: The batch or dataset resource is not found.
          content: {}
        414:
          description: The URL length exceeds the allowed 2000 characters.
          content: {}
        415:
          description: The uploaded file media type isn't supported.
          content: {}
        500:
          description: An internal server error has occurred.
          content: {}
        503:
          description: The service is unavailable.
          content: {}
  /batches/{batchId}:
    post:
      tags:
      - Batch Ingestion
      summary: Finish uploading a file
      description: Small file upload is used for files 256MB or smaller.
      operationId: completeBatch
      parameters:
      - name: Authorization
        in: header
        description: The access token which can be copied from your Experience Platform
          integration, prefixed with "Bearer ". For more information on how to obtain
          this value, visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-api-key
        in: header
        description: The API key which can be copied from your Experience Platform
          integration. For more information on how to obtain this value, visit the
          [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-gw-ims-org-id
        in: header
        description: The Organization ID which can be copied from your Experience
          Platform integration. For more information on how to obtain this value,
          visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
        required: true
        schema:
          type: string
      - name: x-sandbox-name
        in: header
        description: The name of the sandbox in which the operation will take place.
          See the [sandboxes overview documentation](https://adobe.com/go/sandbox-overview-en)
          for more information.
        required: true
        schema:
          type: string
      - name: batchId
        in: path
        description: The ID of the batch that needs to be signalled for completion.
        required: true
        schema:
          type: string
      - name: action
        in: query
        description: The action to take on the batch. To signal that it's completed,
          use 'COMPLETE'.
        required: true
        schema:
          type: string
          enum:
          - COMPLETE
          - ABORT
          - FAIL
          - REVERT
      responses:
        200:
          description: The batch has been successfully promoted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Batch'
        400:
          description: The request is malformed.
          content: {}
        401:
          description: Access is unauthorized. The IMS token provided is invalid.
          content: {}
        404:
          description: The batch is not found.
          content: {}
        414:
          description: The URL length exceeds the allowed 2000 characters.
          content: {}
        500:
          description: An internal server error has occurred.
          content: {}
        503:
          description: The service is unavailable.
          content: {}
components:
  schemas:
    streamingMessage:
      required:
      - DATASET_ID
      - IMS_ORG_ID
      - SCHEMA_ID
      - SCHEMA_VERSION
      type: object
      properties:
        TENANT_ID:
          type: string
          description: This ID is used to ensure that resources you create are properly
            namespaced and contained within your IMS Organization.
        SCHEMA_ID:
          type: string
          description: The ID of the schema that is created.
        SCHEMA_VERSION:
          type: string
          description: The version of the schema that is created.
        IMS_ORG_ID:
          type: string
          description: Your IMS Organization ID can be found under the integration
            details in the Adobe Developer Console.
        DATASET_ID:
          type: string
          description: The ID of the dataset that you want to publish to.
        SOURCE_NAME:
          type: string
          description: The optional name for your source. If this value is missing,
            the streaming message will automatically add the source ID from the streaming
            connection definition.
      description: The message that you want to ingest.
      example:
        header:
          schemaRef:
            id: https://ns.adobe.com/{TENANT_ID}/schemas/{SCHEMA_ID}
            contentType: application/vnd.adobe.xed-full+json;version={SCHEMA_VERSION}
          imsOrgId: '{IMS_ORG_ID}'
          datasetId: '{DATASET_ID}'
          createdAt: "1526283801869"
          source:
            name: '{SOURCE_NAME}'
        body:
          xdmMeta:
            schemaRef:
              id: https://ns.adobe.com/{TENANT_ID}/schemas/{SCHEMA_ID}
              contentType: application/vnd.adobe.xed-full+json;version={SCHEMA_VERSION}
          xdmEntity:
            person:
              name:
                firstName: Jane
                middleName: F
                lastName: Doe
              birthDate: 1969-03-14
              gender: female
            workEmail:
              primary: true
              address: janedoe@example.com
              type: work
              status: active
    File:
      type: object
      properties:
        name:
          type: string
          description: The full path and name of the file you sent in the request.
          example: acme/customers/campaigns/summer.json
        sizeInBytes:
          type: integer
          description: The size in bytes of the file you have uploaded.
          example: 3682
          format: int64
    Column:
      type: object
      properties:
        cid:
          type: string
        name:
          type: string
    FormatParams:
      type: object
      properties:
        delimiter:
          type: string
          description: The character used to specify boundaries between separate strings when parsing column values.
        quote:
          type: string
          description: The character used to quote a value when parsing data.
        escape:
          type: string
          description: The character used to escape a reserved character when parsing data.
        charset:
          type: string
          description: The character encoding used for parsing data.
        header:
          type: boolean
          description: The flag to indicate if the header is supplied in the dataset files.
        format:
          type: string
          description: The file format for the uploaded file.
    Preview:
      type: object
      properties:
        columns:
          type: array
          items:
            $ref: '#/components/schemas/Column'
        rows:
          type: array
          items:
            type: object
            additionalProperties:
              type: string
    PreviewResponse:
      type: object
      properties:
        formatParams:
          $ref: '#/components/schemas/FormatParams'
        preview:
          $ref: '#/components/schemas/Preview'
    Batch:
      # required:
      # - imsOrg
      # - status
      type: object
      properties:
        id:
          type: string
          description: The ID of the batch.
          example: "{BATCH_ID}"
        imsOrg:
          type: string
          description: The ID of your organization.
          example: "{ORG_ID}"
        created:
          type: integer
          description: The Unix timestamp in **milliseconds** when this batch was
            created.
          example: "2022-11-09T18:45:31.256Z"
          readOnly: true
        createdClient:
          type: string
          description: The ID of your client that created this batch.
          example: "{CLIENT_ID}"
          readOnly: true
        createdUser:
          type: string
          description: The ID of the user who created this object.
          example: "{USER_ID}"
          readOnly: true
        updatedUser:
          type: string
          description: The ID of the user who last changed this object.
          example: "{USER_ID}"
          readOnly: true
        updated:
          type: integer
          description: The Unix timestamp in **milliseconds** of the last update.
          example: "2022-11-09T18:45:31.256Z"
          readOnly: true
        started:
          type: integer
          description: The Unix timestamp in **milliseconds** when the batch processing
            action was started.
          example: "2022-11-09T18:45:31.256Z"
        completed:
          type: integer
          description: The Unix timestamp in **milliseconds** when the batch processing
            action was completed. To get the total processing time, subtract the "Started"
            time from the "Completed" time.
          example: "2022-12-09T18:45:31.256Z"
        status:
          type: string
          description: The current status of this batch.
          example: active
          enum:
          - processing
          - active
          - success
          - failed
          - failure
          - queued
          - retrying
          - stalled
        recordCount:
          type: integer
          description: The total number of data records (rows/documents) processed
            in this batch.
          example: 57
        failedRecordCount:
          type: integer
          description: The number of records that could not be processed in this batch.
          example: 3
        errors:
          type: array
          description: Information about errors.
          items:
            $ref: '#/components/schemas/errors'
        size:
          type: integer
          description: The number of bytes processed in this batch.
          example: 1,342,576
        version:
          type: string
          description: The semantic version of the batch. This value is updated when
            the batch is modified.
          example: 1.0.0
          readOnly: true
        availableDates:
          type: object
          properties:
            startDate:
              type: integer
              description: The Unix timestamp in **seconds** for the most recent data
                available in this batch.
              example: "2022-12-09T18:45:31.256Z"
            endDate:
              type: integer
              description: The Unix timestamp in **seconds** for the oldest data available
                in this batch.
              example: "2022-11-09T18:45:31.256Z"
          description: Describes what date range of data is available in the batch.
            This value is null if the dates aren't relevant for data related to this
            batch.
        relatedObjects:
          type: array
          description: A list of the objects involved with this batch.
          items:
            $ref: '#/components/schemas/relatedObjects'
        metrics:
          type: object
          properties: {}
          description: Contains metrics related to this batch.  Metric names are determined
            by the producer of the object since each batch may want to record metrics
            that are relevant to the process.
        tags:
          type: object
          properties: {}
          description: Tags are values associated with a particular object. These
            are generally used by external systems for marking an object in a way
            that it understands.
        inputFormat:
          type: object
          properties:
            format:
              type: string
              enum:
              - parquet
              - json
            delimiter:
              type: string
              description: The character used to specify boundaries between separate strings when parsing column values.
              example: ","
            quote:
              type: string
              description: The character used to quote a value when parsing data.
              example: '"'
            escape:
              type: string
              description: The character used to escape a reserved character when parsing data.
              example: \
            charset:
              type: string
              description: The character encoding used for parsing data.
              example: UTF-8
            header:
              type: boolean
              description: The flag to indicate if the header is supplied in the dataset files.
              example: true
          description: Metadata describing the ingest format of the batch being ingested.
    errors:
      type: object
      properties:
        code:
          type: string
          description: An enumerated code that identifies the type of error encountered.
          example: 405
        rows:
          type: array
          description: Indicates which rows exhibit this error. This could be a single
            number or a hyphen-delimited range.
          items:
            type: string
            description: The row or range of rows that the error was encountered on.
            example: 13-26
        description:
          type: string
          description: A human-readable description of the error.
          example: "HTTP 405 Method Not Allowed"
    relatedObjects:
      type: object
      properties:
        type:
          type: string
          description: The type of object processed in this batch.
          example: dataSet
          enum:
          - batch
          - connection
          - connector
          - dataSet
          - dataSetFile
          - dataSetView
          - transform
        id:
          type: string
          description: The ID of the dataset.
          example: "{DATASET_ID}"
        tag:
          type: string
          properties: {}
          description: 'The name for the relation the specified object had with this
            batch operation. For example: input, output, trigger, etc.'
        status:
          type: string
          description: The current status of the dataset.
          enum:
          - processing
          - active
          - success
          - failed
          - failure
          - queued
          - retrying
          - stalled
        errors:
          type: array
          items:
            $ref: '#/components/schemas/errors'
        metrics:
          type: object
          additionalProperties:
            type: integer
          description: Contains metrics related to the dataset.
    IngestBatch:
      required:
      - datasetId
      - inputFormat
      type: object
      properties:
        datasetId:
          type: string
          description: The ID of the dataset that you are creating a batch
            for. When creating the batch, the files uploaded must conform to 
            the XDM schema of the dataset ID that you provided.
          example: "{DATASET_ID}"
        externalId:
          type: string
          description: A client supplied batch identifier, that is expected to be
            unique within your organization. This defaults to the batch ID if not specified.
          example: "{BATCH_ID}"
        inputFormat:
          type: object
          properties:
            format:
              type: string
              description: The file format of the ingested files.
              example: json
              enum:
              - JSON
              - Parquet
              - CSV
          description: The format of the ingested batch files. It can be any of the following 
            values; `JSON`, `Parquet`, or `CSV`. The example provided is for single-line JSON. To 
            ingest a multi-line JSON file, the `isMultiLineJson` flag must be set to `true`. 
            For more information, please read the batch ingestion 
            [troubleshooting guide](https://experienceleague.adobe.com/docs/experience-platform/ingestion/batch/troubleshooting.html#how-is-multi-line-json-ingested%3F).          
        replay:
          type: object
          properties:
            reason:
              type: string
              description: State the reason for including the batch IDs.
              example: replace
            predecessors:
              type: array
              description: An array of batch IDs to be updated by the request. Any client provided 
                ID in the request body must be prefixed with a `$` to be parameterized.
              items:
                type: string
                example: "${BATCH_ID_A}, ${BATCH_ID_B}"
            predecessorsByExternalId:
              type: array
              description: An array of client batch IDs to be updated by the request. Any client provided 
                ID in the request body must be prefixed with a `$` to be parameterized.
              items:
                type: string
                example: "${CLIENT_BATCH_ID_A}, ${CLIENT_BATCH_ID_B}"
          description: Provide a list of client supplied IDs to identify the previous batches
            that this new batch is replacing. Any client supplied ID as part of the request body
            must be prefixed with a `$`.
        tags:
          type: object
          additionalProperties:
            type: array
            description: Any properties associated with previous batches.
            example: PLACEHOLDER
            items:
              type: string
          description: Additional batch tags. This object contains any properties associated with the previous batches.
    StreamingIngestionResponse:
      type: object
      properties:
        inletID:
          type: string
          description: The ID of the previously created streaming endpoint
        xactionId:
          type: string
          description: The xactionID is a unique identifier generated server-side
            for the XDM record you just sent. This ID helps Adobe trace this record's
            lifecycle through various systems and with debugging.
        receivedTimeMs:
          type: integer
          description: receivedTimeMs is a timestamp in **milliseconds** that shows
            what time the request was received.
          format: int32
      example:
        inletId: '{INLET_ID}'
        xactionId: 1532625558467:0001:13
        receivedTimeMs: "1551307525735"
    BatchMessage:
      type: object
      description: The batch message to be published to Platform.
      example:
        messages:
        - header:
            schemaRef:
              id: https://ns.adobe.com/{TENANT_ID}/schemas/{SCHEMA_ID}
              contentType: application/vnd.adobe.xed-full+json;version={SCHEMA_VERSION}
            imsOrgId: '{IMS_ORG_ID}'
            datasetId: '{DATASET_ID}'
          body:
            xdmMeta:
              schemaRef:
                id: https://ns.adobe.com/{TENANT_ID}/schemas/{SCHEMA_ID}
                contentType: application/vnd.adobe.xed-full+json;version={SCHEMA_VERSION}
            xdmEntity:
              _id: 9af5adcc-db9c-4692-b826-65d3abe68c22
              timestamp: 2019-02-23T22:07:01Z
              environment:
                browserDetails:
                  userAgent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML,
                    like Gecko) Chrome/29.0.1547.57 Safari/537.36 OPR/16.0.1196.62
                  acceptLanguage: en-US
                  cookiesEnabled: "true"
                  javaScriptVersion: "1.6"
                  javaEnabled: true
                colorDepth: 32
                viewportHeight: 799
                viewportWidth: 414
              productListItems:
              - SKU: CC
                name: Fernie Snow
                quantity: 30
                priceTotal: 7.8
              commerce:
                productViews:
                  value: 1
              _experience:
                campaign:
                  message:
                    profileSnapshot:
                      workEmail:
                        address: janedoe@example.com
    BatchResponseDTO:
      type: object
      properties:
        inletId:
          type: string
          description: The streaming connection where the message is going to be published
            to.
          example: 9b0cb233972f3b0092992284c7353f5eead496218e8441a79b25e9421ea127f5
        batchId:
          type: string
          description: The UUID assigned to the batch messages.
          example: 1565638336649:1750:244
        receivedTimeMs:
          type: integer
          description: Timestamp in **milliseconds** when Data Collection Services
            received the message.
          example: 1565638336705
        responses:
          type: array
          description: responseObject
          items:
            $ref: '#/components/schemas/BatchResponseMessage'
      description: Batch message to be published to Data Collection Services
    BatchResponseMessage:
      type: object
      properties:
        xactionId:
          type: string
          description: The UUID assigned to the message.
          example: 1565650704337:2124:92:3
      description: The response to an ingested batch.
  parameters:
    authorization:
      name: Authorization
      in: header
      description: The access token which can be copied from your Experience Platform
        integration, prefixed with "Bearer ". For more information on how to obtain
        this value, visit the [authentication tutorial](http://www.adobe.com/go/platform-api-authentication-en).
      required: true
      schema:
        type: string
    x-gw-ims-org-id:
      name: x-gw-ims-org-id
      in: header
      description: The Organization ID which can be copied from your Experience Platform
        integration. For more information on how to obtain this value, visit the [authentication
        tutorial](http://www.adobe.com/go/platform-api-authentication-en).
      required: true
      schema:
        type: string
    x-api-key:
      name: x-api-key
      in: header
      description: The API key which can be copied from your Experience Platform integration.
        For more information on how to obtain this value, visit the [authentication
        tutorial](http://www.adobe.com/go/platform-api-authentication-en).
      required: true
      schema:
        type: string
    x-sandbox-name:
      name: x-sandbox-name
      in: header
      description: The name of the sandbox in which the operation will take place.
        See the [sandboxes overview documentation](https://adobe.com/go/sandbox-overview-en)
        for more information.
      required: true
      schema:
        type: string
    json-header:
      name: Content-Type
      in: header
      description: application/json
      required: true
      schema:
        type: string
    json-smile-header:
      name: Content-Type
      in: header
      description: The media type being sent in the request payload. For JSON formatted
        payloads the value must be set to application/json. The endpoint also accepts
        payloads encoded in Smile format, which requires the value to be set to application/x-jackson-smile.
      required: true
      schema:
        type: string
        enum:
        - application/json
        - application/x-jackson-smile
